### ISSUE TITLE
Composer 2 support

### ISSUE THREAD

**Issue by simonberger** [simplesamlphp/composer-module-installer#14]
This plugin does not work with composer 2 (snapshot) which requires api version 2.

https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-integrators-and-plugin-authors

**Comment by tvdijen** [comment]
Thanks for reporting Simon! At this point we don't have the resources to put any effort in Alpha versions.. contributions are most welcome

**Comment by tvdijen** [comment]
@simonberger v1.1.7 should solve the issue.. Our dependencies will have to do the same.. Right now a SimpleSAMLphp installation breaks on the Psalm-dependency
