### ISSUE TITLE
Version  v1.1.12 requires PHP 7.4 without stating the dependency

### ISSUE THREAD

**Issue by akinspe** [simplesamlphp/composer-module-installer#19]
Version 1.1.12 was released on 8/31 and uses Property types in ModuleInstallerPlugin.php however it does not indicate that it requires php 7.4 or above and therefore may get installed in systems running earlier versions and fails.

Since this is a backward compatible change. this may break many workflows. At very least you need to introduce a php version dependency in composer.json.

The following error is shown when installing in PHP 7.3 (which is permitted based on the composer.json dependencies)

```
Parse error: syntax error, unexpected 'ModuleInstaller' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in vendor/simplesamlphp/composer-module-installer/src/ModuleInstallerPlugin.php on line 15
```

**Comment by tvdijen** [comment]
I've removed the tag and released a new 1.2.0 with the php requirement in place. Sorry for the inconvenience!
