### ISSUE TITLE
Issue updating from 1.2 to 1.3

### ISSUE THREAD

**Issue by mrbase** [simplesamlphp/composer-module-installer#23]
When we update our simplesaml to 1.3 all modules are installed into the root of our project.
I can prevent it by fixing the version in composer.json to 1.2.0 - but why the change in module install path?

It seems to me that `ModuleInstaller::getPackageBasePath` might be guessing the incorrect path.

The only simplesaml requirement we have is on "simplesamlphp/simplesamlphp": "~1.18"

**Comment by tvdijen** [comment]
Sounds like the same problem as #17 .. We have however never been able to reproduce this

**Comment by tvdijen** [comment]
I'm not sure I follow..  I create an empty project and require simplesamlphp/simplesamphp: ~1.18..
Next, I run `composer update`.. Nothing happens.. Are you manually trying to update the composer-module-installer or something?

**Comment by mrbase** [comment]
I have isolated the dependencies that seems to trigger the issue not sure why tho.
However it seems that specifying an alternative vendor-dir is part of the reason.

It also installs simplesamlphp/composer-module-installer v1.3.2 even tho the simplesamlphp/simplesamphp is set to ~1.8
The only way I can get it to install version 1.2 is by adding it to the require list.

If i fix the version to 1.2, the the modules folder is added to the correct location and not in the root folder.

Running this on PHP 7.4 btw, we are in the process of upgrading to 8.

```json
{
  "config": {
    "vendor-dir": "alternative/vendor",
    "allow-plugins": {
      "simplesamlphp/composer-module-installer": true
    }
  },
  "require": {
    "php": ">=7.4",
    "simplesamlphp/simplesamlphp": "~1.18"
  },
  "require-dev": {
    "symfony/dom-crawler": "^3.4"
  },
  "prefer-stable": true
}
```

**Comment by tvdijen** [comment]
Could you try locking it to `dev-bugfix/fix-find-module-path` and see if this changes anything?

**Comment by mrbase** [comment]
Simplesaml or the installer?

**Comment by mrbase** [comment]
Yeah, then the php version is off.
I would like to have the packages up-2-date before we make the switch to 8.
simplesamlphp/simplesamlphp dev-master requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.

**Comment by tvdijen** [comment]
No no no, I mean `dev-master` of the `composer-module-installer`

**Comment by mrbase** [comment]
Oh, sorry - like this?

```json
{
  "config": {
    "vendor-dir": "alternative/vendor",
    "allow-plugins": {
      "simplesamlphp/composer-module-installer": true
    }
  },
  "require": {
    "php": ">=7.4",
    "simplesamlphp/composer-module-installer": "dev-master",
    "simplesamlphp/simplesamlphp": "~1.18"
  },
  "require-dev": {
    "symfony/dom-crawler": "^3.4"
  },
  "prefer-stable": true
}
```

If I do that, the output is:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - simplesamlphp/simplesamlphp[v1.18.0, ..., v1.19.4] require simplesamlphp/simplesamlphp-module-authcrypt ^0.9 -> satisfiable by simplesamlphp/simplesamlphp-module-authcrypt[v0.9.0, ..., v0.9.4].
    - simplesamlphp/simplesamlphp[v1.19.5, ..., v1.19.7] require simplesamlphp/simplesamlphp-module-adfs ^1.0 -> satisfiable by simplesamlphp/simplesamlphp-module-adfs[v1.0.0, ..., v1.0.9].
    - simplesamlphp/simplesamlphp v1.19.6 requires gettext/gettext v4.x-dev#3e7460f8d9c90174824e3f39240bd578bb3d376a -> found gettext/gettext[4.x-dev] but it does not match your minimum-stability.
    - simplesamlphp/simplesamlphp-module-authcrypt[v0.9.0, ..., v0.9.4] require simplesamlphp/composer-module-installer ~1.1 -> found simplesamlphp/composer-module-installer[v1.1.0, ..., v1.3.2] but it conflicts with your root composer.json require (dev-master).
    - simplesamlphp/simplesamlphp-module-adfs[v1.0.0, ..., v1.0.4] require simplesamlphp/composer-module-installer ~1.1 -> found simplesamlphp/composer-module-installer[v1.1.0, ..., v1.3.2] but it conflicts with your root composer.json require (dev-master).
    - simplesamlphp/simplesamlphp-module-adfs[v1.0.5, ..., v1.0.9] require simplesamlphp/composer-module-installer ^1.1.7 -> found simplesamlphp/composer-module-installer[v1.1.7, ..., v1.3.2] but it conflicts with your root composer.json require (dev-master).
    - Root composer.json requires simplesamlphp/simplesamlphp ~1.18 -> satisfiable by simplesamlphp/simplesamlphp[v1.18.0, ..., v1.19.7].
```

**Comment by tvdijen** [comment]
Crap, classic catch-22... I'd rather not tag a new release until I know something work, but I don't see a way around this.. I've release v1.3.3.. Try that one

**Comment by mrbase** [comment]
Just tried again, and it works as expected now - both with and without the installer as a requirement.
Thanks a lot :+1:
