### ISSUE TITLE
Do not recognise repositories set in modules composer.json

### ISSUE THREAD

**Issue by moffe42** [simplesamlphp/composer-module-installer#5]
I you add a repository in the composer.json for a module (usually a private one), the the module do not pick it up, when it install the module, resulting in Composer not being able to resolve the required package.

**Comment by jaimeperez** [comment]
Hi @moffe42!

Can you be more specific? I have plenty of modules installed from a private repository, both in my development box, and also in our production IdP, and it works just fine.
