### ISSUE TITLE
Feature request - enable inbuilt modules

### ISSUE THREAD

**Issue by jeremyfrench** [simplesamlphp/composer-module-installer#6]
If I am installing simplesamlphp via composer, I may also want to enable some of the modules that come bundled with it. At the moment there seems to be no composer friendly way to do this, would the ability to enable (and disable) the modules that come with the simplesaml package be a feature that this tool would want to do (or should I write my own)

**Comment by jaimeperez** [comment]
Hi @jeremyfrench!

Currently, we always recommend that modules installable through composer are enabled by default, but of course, it might be that some modules are not.

Enabling a module while we are installing it with the `composer-module-installer` should be trivial (just a matter of adding a file named `enable` to the root of the module, in case the module is disabled by default, that is, it has a file named `default-disable` on its root). Pull requests are always welcome 😉

**Comment by jaimeperez** [comment]
The old `enable`, `default-enable`, etc files have been deprecated in favour of the `module.enable` configuration setting in `config.php`. There are situations where indeed it's preferrable to be able to enable/disable modules despite them being installed, so I'm closing this as a _won't fix_.
